"""G11A clauses 15-17: contract drift (record-only), seam invariance, protocol.

Clause 15 is deliberately *half* of named new work item 29. The ``interfaces``
field lands in G11B with the renderer that populates it, because "a schema field
no code can fill is not evidence of anything" — an earlier draft of the gate had
it here and would have dispatched a field that could only ever be absent.

Clause 16 is a claim about what this stage did **not** add: no geom service. It
is asserted rather than stated because §10's list of non-changes is exactly the
kind of claim that rots silently.

Clause 17 is the one real protocol change, ``geom_type`` on every
``tag_fingerprints`` entry. §10 used to let one sentence cover both the sandbox
contract and the §8 worker result protocol; they are different contracts, and
this clause pins the one that moved.
"""

from __future__ import annotations

import re
import subprocess
import sys
from collections.abc import Iterator
from pathlib import Path
from typing import Any, cast

import pytest
from _g11a import (
    DATASHEET,
    REPO,
    SHIPPED_PARTS,
    component_tree,
    motor_component,
    requires_bwrap,
)
from hephaestus.contract import toolgen, tools_decl
from hephaestus.core.executor.fingerprint import GEOM_TYPES, TagDescriptor
from hephaestus.core.registry import RegistryOps, RegistrySet, load_registry

from opstore import OpStore

# ==========================================================================
# clause 15 — contract drift, record-only half


def test_the_tool_count_is_unchanged_by_this_stage() -> None:
    """§3: two result schemas grow; no tool is added. That is the whole point
    of putting the capability in the result rather than on the surface.

    The literal moved 53 -> 54 when MESH_INGEST.md §7.2 (Stage 12C) added
    ``compare_to_scan``. What THIS clause pins is unchanged and is asserted
    directly: Stage 11 adds no tool of its own.
    """
    assert len(tools_decl.tool_names()) == 54
    assert "compare_to_scan" in tools_decl.tool_names()


def test_the_generated_artifacts_regenerate_identically() -> None:
    """All five: the JSON schemas, the TypeBox module, the MCP file, the docs.

    The declaration is artifact one and the source of the other four, so the
    per-tool schema set is asserted to *be* the declared tool set rather than
    merely to regenerate — a tool declared and never generated would otherwise
    pass every equality below.
    """
    generated = toolgen.generate_json_schemas()
    assert generated == toolgen.generate_json_schemas(), "generation is not deterministic"
    assert {Path(rel).name.removesuffix(".schema.json") for rel in generated} == set(
        tools_decl.tool_names()
    )
    for rel, text in generated.items():
        assert (REPO / rel).read_text(encoding="utf-8") == text, f"{rel} is stale; rerun toolgen"
    ts = (REPO / "agent" / "src" / "tools" / "schema.gen.ts").read_text(encoding="utf-8")
    assert ts == toolgen.generate_typebox_module(), "schema.gen.ts is stale; rerun toolgen"
    mcp = (REPO / "schemas" / "mcp" / "tools.json").read_text(encoding="utf-8")
    assert mcp == toolgen.generate_mcp_document(), "schemas/mcp/tools.json is stale; rerun toolgen"


def _tool_schema_md() -> str:
    return (REPO / "tool_schema.md").read_text(encoding="utf-8")


def test_the_fifth_artifact_is_reached_by_this_gates_own_command() -> None:
    """``tool_schema.md`` — the fifth of the five, and the one this gate's command
    did not reach.

    It is not generated by ``toolgen``; it is hand-maintained under a drift test
    (``contract/tests/test_toolgen.py``), and that suite is not part of either
    stage-11 gate's command. So the clause asserted "the five regenerate
    identically" while its own command could only see three of them. The drift
    contract is re-asserted here, in this gate, over the artifact this stage
    edited (the Amendment manifest's `tool_schema.md:1101-1114` row).
    """
    md = _tool_schema_md()
    declared = set(tools_decl.tool_names())
    excluded = set(tools_decl.STAGE2_EXCLUDED_TOOLS)

    # Every declared tool has a signature at column 0 inside a fence.
    signatures = set(re.findall(r"^([a-z][a-z0-9_]+)\(", md, re.MULTILINE))
    assert declared <= signatures, f"undocumented tools: {sorted(declared - signatures)}"

    # Every documented tool heading is declared, minus the recorded exclusions.
    headings: set[str] = set()
    for line in md.splitlines():
        if line.startswith("### "):
            headings |= {
                token.strip()
                for token in line[4:].split("/")
                if re.fullmatch(r"[a-z][a-z0-9_]+", token.strip())
            }
    assert not headings - excluded - declared, f"documented but undeclared: {headings - declared}"
    assert declared.isdisjoint(excluded)


@pytest.mark.parametrize(
    "field",
    ["component_class", "series", "mass_g", "has_datasheet", "mass", "datasheet"],
)
def test_the_fifth_artifact_documents_this_stages_record_only_fields(field: str) -> None:
    """Drift-clean in general is not the same claim as "this stage's edit landed".

    The Amendment manifest says the two result shapes gain these fields; a doc
    that stayed silent about them would pass the drift test above unchanged,
    because that test keys on tool *names*.
    """
    assert field in _tool_schema_md()


@pytest.mark.parametrize(
    ("tool", "field"),
    [
        ("search_parts_store", "component_class"),
        ("search_parts_store", "series"),
        ("search_parts_store", "mass_g"),
        ("search_parts_store", "has_datasheet"),
        ("instance_store_part", "mass"),
        ("instance_store_part", "datasheet"),
    ],
)
def test_the_record_only_fields_are_declared_and_optional(tool: str, field: str) -> None:
    """Optional because a *legacy* part carries none of them — a caller branches
    on presence, and a required field would have forced an empty stand-in."""
    document = toolgen.schema_document(tools_decl.get_tool(tool))
    result = cast("dict[str, Any]", document["result"])
    variants = cast("list[dict[str, Any]]", result.get("oneOf") or [result])
    found = False
    for variant in variants:
        if variant.get("type") == "array":
            variant = cast("dict[str, Any]", variant.get("items", {}))
        properties = cast("dict[str, Any]", variant.get("properties", {}))
        if field in properties:
            found = True
            assert field not in cast("list[str]", variant.get("required", []))
    assert found, f"{tool} does not declare {field!r}"


def test_the_interfaces_field_is_g11bs_half_of_item_29() -> None:
    """Repointed by G11B, which is the sub-stage the item-29 split assigns it to.

    While A stood alone this asserted ``interfaces`` was ABSENT: a schema field
    no code can fill is not evidence of anything, and G11A has no renderer that
    emits an interface tag. G11B ships that renderer and item 11's record ⇄
    region equality, so the field is now populated and G11B clause 17 asserts
    its shape and its dispatch. What survives here unchanged is A's own half —
    the record-only fields above — and the reason the split existed.
    """
    document = toolgen.schema_document(tools_decl.get_tool("instance_store_part"))
    result = cast("dict[str, Any]", document["result"])
    variants = cast("list[dict[str, Any]]", result.get("oneOf") or [result])
    declared = [
        variant
        for variant in variants
        if "interfaces" in cast("dict[str, Any]", variant.get("properties", {}))
    ]
    assert len(declared) == 1, "exactly the ok variant carries it"
    assert "interfaces" not in cast("list[str]", declared[0].get("required", []))


def test_search_advertises_the_declared_interfaces_once_the_region_backs_them(
    tmp_path: Path,
) -> None:
    """Also repointed by G11B, for the reason the split named.

    Until record ⇄ region set equality landed, a declared interface name was not
    evidence that the generator emits a tag for it, so returning the list would
    have advertised anchors that may not exist. It is evidence now — the index
    refuses the record otherwise — so the row carries the names, unprefixed.
    """
    from _g11a import index_of

    root = component_tree(tmp_path / "parts", motor_component())
    row = index_of(root).get("stepper_nema17_frame").search_result()
    assert row["component_class"] == "motor"
    interfaces = cast("list[dict[str, Any]]", row["interfaces"])
    assert [entry["name"] for entry in interfaces] == ["mount_face", "shaft"]


@pytest.fixture
def dispatch_bench(tmp_path: Path) -> Iterator[Any]:
    """The real dispatcher over a registry set carrying one component record."""
    from hephaestus.agent_bridge.cad_ops import CadOps
    from hephaestus.agent_bridge.dispatch import ToolDispatcher
    from hephaestus.core.project_store.layout import load_project, open_store
    from hephaestus.core.project_store.store import ProjectStore
    from hephaestus.testing.tools_fixture import scaffold

    parts = component_tree(
        tmp_path / "parts",
        motor_component(
            datasheet=DATASHEET,
            mass={"value_g": 280.0, "source": "datasheet", "com_mm": [0.0, 0.0, -19.5]},
        ),
    )
    root = tmp_path / "proj"
    scaffold(root)
    layout = load_project(root)
    store = open_store(layout)
    registries = RegistrySet({"parts": load_registry(parts)})
    dispatcher = ToolDispatcher(
        ProjectStore(layout, store),
        cad=CadOps(layout, store),
        registry=RegistryOps(registries, store),
    )

    class Bench:
        def __init__(self) -> None:
            self._n = 0

        def call(self, tool: str, arguments: dict[str, Any], principal: Any) -> Any:
            self._n += 1
            return dispatcher.dispatch(
                principal,
                {
                    "session_id": principal.session_id,
                    "run_id": "run-1",
                    "tool": tool,
                    "arguments": arguments,
                    "invocation": {
                        "session_id": principal.session_id,
                        "entry_id": f"entry-{self._n}",
                        "ordinal": 1,
                        "provider_call_id": "call_0",
                    },
                },
            )

    try:
        yield Bench()
    finally:
        store.close()


def _principals() -> list[Any]:
    from hephaestus.testing.tools_fixture import ORCH, PART_WIDGET, QUICK_WIDGET

    return [ORCH, PART_WIDGET, QUICK_WIDGET]


@pytest.mark.parametrize("principal_index", [0, 1, 2])
def test_every_profile_dispatches_the_record_only_search_fields(
    dispatch_bench: Any, principal_index: int
) -> None:
    principal = _principals()[principal_index]
    rows = cast(
        "list[dict[str, Any]]",
        dispatch_bench.call("search_parts_store", {"query": "fixture component"}, principal),
    )
    assert rows, "the fixture component must be findable"
    row = rows[0]
    assert row["component_class"] == "motor"
    assert cast("dict[str, Any]", row["series"])["family"] == "nema"
    assert row["mass_g"] == 280.0
    assert row["has_datasheet"] is True


@requires_bwrap
def test_the_instance_result_carries_mass_and_datasheet_verbatim(tmp_path: Path) -> None:
    """Verbatim, because neither is a measurement: §5 and §7.4 both say so."""
    from hephaestus.core.executor.sandbox.bwrap import BwrapBackend

    mass = {"value_g": 280.0, "source": "datasheet", "com_mm": [0.0, 0.0, -19.5]}
    parts = component_tree(tmp_path / "parts", motor_component(datasheet=DATASHEET, mass=mass))
    store = OpStore.create(tmp_path / "store")
    try:
        ops = RegistryOps(
            RegistrySet({"parts": load_registry(parts)}),
            store,
            backend=BwrapBackend(),
            scratch_root=tmp_path / "scratch",
        )
        result = ops.instance_store_part("stepper_nema17_frame", {}, None, "motor_a")
        prefix = "motor_a"
        assert result["mass"] == mass
        assert result["datasheet"] == DATASHEET
        # G11C's half is absent, not half-wired.
        assert "claims" not in result
        # `interfaces` IS present now: G11B clause 17 delivered item 29's other
        # half, and this clause's subject is the two blocks above being verbatim.
        assert result["interfaces"] == [
            f"{prefix}__mount_face",
            f"{prefix}__shaft",
        ]
    finally:
        store.close()


# ==========================================================================
# clause 16 — seam invariance: this stage adds no geom service


def test_the_geom_import_boundary_suite_passes_unchanged() -> None:
    completed = subprocess.run(
        [sys.executable, "-m", "pytest", "core/tests/test_geom_import_boundary.py", "-q"],
        cwd=REPO,
        capture_output=True,
        text=True,
        check=False,
    )
    assert completed.returncode == 0, completed.stdout[-4000:] + completed.stderr[-2000:]


def test_the_geom_seam_holds_exactly_the_declared_pure_services() -> None:
    """§10: "this stage adds nothing to the nine pure services". Enumerated, so
    the claim fails here if a later edit smuggles one in unannounced.

    The list moved from nine to eleven, and both additions are declared by a
    later stage rather than by this one: ``MESH_INGEST.md`` §2.1 adds
    ``geom.mesh`` as the tenth pure service (external triangles -> facts, the
    mission rule 6 seam against ``render.tessellate``) and §4 adds
    ``geom.mesh_solid`` as the eleventh (the OCCT half — sew, the
    ``BRepCheck_Analyzer`` gate, the loft). What THIS clause pins is unchanged:
    Stage 11 adds none of them, and every name below is still here.
    """
    package = REPO / "core" / "src" / "hephaestus" / "geom"
    services = sorted(path.stem for path in package.glob("*.py") if path.stem != "__init__")
    assert services == [
        "compare",
        "constraints",
        "kerf",
        "kinematics",
        "measure",
        "mesh",
        "mesh_solid",
        "metrics",
        "nesting",
        "step_io",
        "topology",
    ]


# ==========================================================================
# clause 17 — worker protocol drift


def test_geom_type_is_a_closed_set_on_every_descriptor() -> None:
    assert GEOM_TYPES == ("PLANE", "CYLINDER", "CIRCLE", "LINE", "OTHER")


@pytest.mark.parametrize("geom_type", GEOM_TYPES)
def test_a_descriptor_round_trips_its_geom_type(geom_type: str) -> None:
    descriptor = TagDescriptor(
        kind="face",
        point=(0.0, 0.0, 0.0),
        scalar=1.0,
        normal=(0.0, 0.0, 1.0),
        geom_type=geom_type,
    )
    payload = descriptor.to_json()
    assert payload["geom_type"] == geom_type
    assert TagDescriptor.from_json(payload) == descriptor


def test_an_out_of_set_geom_type_is_refused_at_parse() -> None:
    from hephaestus.core.errors import ValidationError

    with pytest.raises(ValidationError) as caught:
        TagDescriptor.from_json(
            {"kind": "face", "point": [0.0, 0.0, 0.0], "scalar": 1.0, "geom_type": "TORUS"}
        )
    assert "geom_type" in caught.value.message
    for member in GEOM_TYPES:
        assert member in caught.value.message


def test_a_descriptor_recorded_before_this_stage_still_parses() -> None:
    """Absent => OTHER. A published bundle predating the field must stay
    loadable, or an existing project's fingerprint baseline breaks."""
    descriptor = TagDescriptor.from_json({"kind": "solid", "point": [0.0, 0.0, 0.0], "scalar": 8.0})
    assert descriptor.geom_type == "OTHER"


def test_a_published_build_round_trips_geom_type(tmp_path: Path) -> None:
    """The field survives ``publication.py``'s ``tag_fingerprints`` write and the
    baseline read back off it — the leg that makes it usable *after* the worker
    that computed it has exited."""
    from hephaestus.core.executor.runner import BuildRequest, run_build
    from hephaestus.core.executor.sandbox.unsafe import UnsafeLocalBackend
    from hephaestus.core.project_store.layout import load_project, open_store
    from hephaestus.core.project_store.publication import Publisher
    from hephaestus.testing.tools_fixture import scaffold

    root = tmp_path / "proj"
    scaffold(root)
    script = (
        "plate = Box(40, 40, 10)\n"
        "bored = plate - Cylinder(radius=5.0, height=40)\n"
        'tag(bored.faces().filter_by(GeomType.CYLINDER)[0], "bore_face")\n'
        'tag(bored.faces().filter_by(GeomType.PLANE).sort_by(SortBy.AREA)[-1], "top_face")\n'
        "part.geometry = bored\n"
    )
    (root / "parts" / "plate.py").write_text(script, encoding="utf-8")
    layout = load_project(root)
    store = open_store(layout)
    try:
        publisher = Publisher(layout, store)
        frozen = publisher.freeze_inputs("plate")
        build = run_build(
            BuildRequest(part="plate", script=frozen.script, globals_source=frozen.globals_source),
            backend=UnsafeLocalBackend(),
            out_dir=layout.store_root / "builds" / "plate-1",
        )
        assert build.result.status == "ok", build.result.error
        assert build.tag_fingerprints["bore_face"].geom_type == "CYLINDER"
        outcome = publisher.publish_build(build, op_id="pub-1")
        assert outcome.kind == "current", outcome.details

        baseline = publisher.baseline_for("plate")
        assert baseline is not None
        reloaded = dict(baseline.descriptors)
        assert reloaded["bore_face"].geom_type == "CYLINDER"
        assert reloaded["top_face"].geom_type == "PLANE"
    finally:
        store.close()


def test_the_worker_computes_geom_type_from_the_real_adaptor(tmp_path: Path) -> None:
    """In the worker, where the shape lives: the scratch tree holding the BRep
    is deleted in a ``finally`` before any caller sees it, so nowhere else
    *can* compute this."""
    from hephaestus.core.executor import worker

    out = tmp_path / "out"
    out.mkdir()
    script = (
        "plate = Box(30, 20, 6)\n"
        "bore = Cylinder(3, 20)\n"
        "body = plate - bore\n"
        "tag(body.faces().filter_by(GeomType.PLANE).sort_by(SortBy.AREA)[-1], 'top')\n"
        "tag(body.faces().filter_by(GeomType.CYLINDER)[0], 'bore')\n"
        "tag(body.edges().filter_by(GeomType.CIRCLE)[0], 'rim')\n"
        "tag(body.edges().filter_by(GeomType.LINE).sort_by(SortBy.LENGTH)[-1], 'edge')\n"
        "tag(body.solids()[0], 'whole')\n"
        "part.geometry = body\n"
    )
    result = worker.execute_job(
        {
            "part": "unit",
            "script": script,
            "globals_source": None,
            "part_overrides": {},
            "project_overrides": {},
            "out_dir": str(out),
        }
    )
    assert result["status"] == "ok", result.get("error")
    fingerprints = cast("dict[str, Any]", result["tag_fingerprints"])
    observed = {
        name: (cast("dict[str, Any]", entry)["kind"], cast("dict[str, Any]", entry)["geom_type"])
        for name, entry in fingerprints.items()
    }
    assert observed == {
        "top": ("face", "PLANE"),
        "bore": ("face", "CYLINDER"),
        "rim": ("edge", "CIRCLE"),
        "edge": ("edge", "LINE"),
        "whole": ("solid", "OTHER"),
    }
    for _name, entry in fingerprints.items():
        assert cast("dict[str, Any]", entry)["geom_type"] in GEOM_TYPES


def test_the_pinned_worker_protocol_suite_passes_with_the_new_field() -> None:
    completed = subprocess.run(
        [sys.executable, "-m", "pytest", "core/tests/test_worker_protocol.py", "-q"],
        cwd=REPO,
        capture_output=True,
        text=True,
        check=False,
    )
    assert completed.returncode == 0, completed.stdout[-4000:] + completed.stderr[-2000:]


def test_the_shipped_parts_tree_is_still_indexed_by_the_same_index() -> None:
    """Rule 6: one store. The component record is a richer ``parts`` entry, not
    a second registry kind — ``BUNDLED_KINDS`` and ``RegistryKind`` are
    untouched, which is what makes that claim checkable."""
    from hephaestus.core.registry import BUNDLED_KINDS

    assert BUNDLED_KINDS == ("skills", "parts", "materials", "dfm")
    assert load_registry(SHIPPED_PARTS).kind == "parts"
