"""Static contracts for the reproducible OCI executor package and image."""

from __future__ import annotations

import hashlib
import json
import re
import runpy
import tomllib
from pathlib import Path

import pytest
from hephaestus.core.executor.sandbox.oci import AUDITED_ENTRYPOINT, AUDITED_IMAGE_ENV
from hephaestus.core.executor.sandbox.oci_launcher import FIXED_WORKER_ENV

ROOT = Path(__file__).resolve().parents[2]
EXECUTOR = ROOT / "docker" / "executor"


def test_executor_distribution_has_worker_only_metadata() -> None:
    config = tomllib.loads((EXECUTOR / "package" / "pyproject.toml").read_text())
    project = config["project"]
    assert project["name"] == "hephaestus-executor-runtime"
    assert project["requires-python"] == ">=3.13,<3.14"
    assert config["build-system"]["requires"] == ["hatchling==1.32.4"]
    dependencies = {item.split("<", 1)[0].split(">", 1)[0] for item in project["dependencies"]}
    assert dependencies == {"build123d", "ezdxf", "numpy", "opstore", "scipy", "trimesh"}
    core = tomllib.loads((ROOT / "core" / "pyproject.toml").read_text())
    opstore = tomllib.loads((ROOT / "opstore" / "pyproject.toml").read_text())
    assert project["version"] == core["project"]["version"] == opstore["project"]["version"]
    text = json.dumps(config, sort_keys=True).lower()
    for excluded in (
        "hephaestus-server",
        "pillow",
        "pygltflib",
        "pyrender",
        "vtk",
    ):
        assert excluded not in text


def test_hashed_dependency_lock_is_closed_and_renderer_free() -> None:
    lock = (EXECUTOR / "requirements.lock").read_text(encoding="utf-8")
    assert "autogenerated by uv" in lock
    assert "--hash=sha256:" in lock
    assert "placeholder" not in lock.lower()
    assert not re.search(r"(?m)^\s*(-e |https?://|file:|\.\.?/)", lock)
    for excluded in ("pillow", "pygltflib", "pyrender", "vtk"):
        assert re.search(rf"(?m)^{excluded}==", lock.lower()) is None

    records = re.split(r"\n(?=[a-zA-Z0-9])", lock)
    requirements = [record for record in records if re.match(r"[a-zA-Z0-9]", record)]
    assert requirements
    assert all("--hash=sha256:" in record for record in requirements)


def test_hashed_build_lock_pins_the_executor_backend() -> None:
    lock = (EXECUTOR / "build-requirements.lock").read_text(encoding="utf-8")
    assert lock.startswith("hatchling==1.32.4 \\\n")
    assert "--hash=sha256:" in lock
    records = re.split(r"\n(?=[a-zA-Z0-9])", lock)
    assert all("--hash=sha256:" in record for record in records)


def test_executor_dockerfile_policy_is_exact() -> None:
    dockerfile = (EXECUTOR / "Dockerfile").read_text(encoding="utf-8")
    from_lines = [line for line in dockerfile.splitlines() if line.startswith("FROM ")]
    assert len(from_lines) == 2
    assert all(re.search(r"@sha256:[0-9a-f]{64}(?:\s|$)", line) for line in from_lines)
    assert "# syntax=" not in dockerfile
    assert dockerfile.count("COPY --from=install") == 1
    assert "COPY --from=install /opt/hephaestus /opt/hephaestus" in dockerfile
    assert "USER 65532:65532" in dockerfile
    assert dockerfile.count("CMD []") == 1
    assert "--network=none" in dockerfile
    for option in ("--no-index", "--no-deps", "--only-binary", "--require-hashes"):
        assert option in dockerfile
    for forbidden in ("apt-get", "curl ", "wget ", "git clone", "COPY agent", "COPY web"):
        assert forbidden not in dockerfile

    entrypoint = re.search(r"ENTRYPOINT\s*(\[[^]]+\])", dockerfile)
    assert entrypoint is not None
    assert tuple(json.loads(entrypoint.group(1))) == AUDITED_ENTRYPOINT
    loader_path = FIXED_WORKER_ENV["LD_LIBRARY_PATH"]
    assert f"LD_LIBRARY_PATH={loader_path}" in AUDITED_ENTRYPOINT
    assert f"'LD_LIBRARY_PATH={loader_path}'" in dockerfile
    assert "*'not found'*" in dockerfile


def test_local_wheel_lock_is_hash_bearing(tmp_path: Path) -> None:
    wheelhouse = tmp_path / "wheelhouse"
    wheelhouse.mkdir()
    executor = wheelhouse / "hephaestus_executor_runtime-0.1.0-py3-none-any.whl"
    opstore = wheelhouse / "opstore-0.1.0-py3-none-any.whl"
    executor.write_bytes(b"executor-wheel")
    opstore.write_bytes(b"opstore-wheel")
    namespace = runpy.run_path(str(EXECUTOR / "write_local_lock.py"))
    target = namespace["write_local_lock"](wheelhouse)
    lines = target.read_text(encoding="ascii").splitlines()
    assert lines[1] == (
        "hephaestus-executor-runtime==0.1.0 --hash=sha256:"
        + hashlib.sha256(b"executor-wheel").hexdigest()
    )
    assert lines[2] == (
        "opstore==0.1.0 --hash=sha256:" + hashlib.sha256(b"opstore-wheel").hexdigest()
    )


def test_native_runtime_locks_are_arch_specific_and_renderer_free() -> None:
    for architecture in ("amd64", "arm64"):
        value = json.loads(
            (EXECUTOR / f"native-{architecture}.lock.json").read_text(encoding="utf-8")
        )
        assert value["architecture"] == architecture
        packages = value["packages"]
        assert packages
        assert len({item["filename"] for item in packages}) == len(packages)
        assert any(item["filename"].startswith("libgl1_") for item in packages)
        assert any(item["filename"].startswith("fonts-dejavu-core_") for item in packages)
        for item in packages:
            assert item["url"].startswith("https://deb.debian.org/")
            assert re.fullmatch(r"[0-9a-f]{64}", item["sha256"])
            assert type(item["size"]) is int and item["size"] > 0
            filename = item["filename"].lower()
            assert "mesa" not in filename
            assert "egl" not in filename
            assert filename.endswith((f"_{architecture}.deb", "_all.deb"))


def test_native_runtime_verifier_rejects_tampering(tmp_path: Path) -> None:
    payload = b"locked-deb"
    package = "example_1_amd64.deb"
    lock = tmp_path / "native-amd64.lock.json"
    lock.write_text(
        json.dumps(
            {
                "architecture": "amd64",
                "packages": [
                    {
                        "filename": package,
                        "sha256": hashlib.sha256(payload).hexdigest(),
                        "size": len(payload),
                        "url": "https://deb.debian.org/debian/pool/example.deb",
                    }
                ],
            }
        ),
        encoding="utf-8",
    )
    artifacts = tmp_path / "artifacts"
    artifacts.mkdir()
    (artifacts / package).write_bytes(payload)
    namespace = runpy.run_path(str(EXECUTOR / "fetch_native_runtime.py"))
    namespace["verify"](lock, artifacts, "amd64")
    (artifacts / package).write_bytes(b"tampered")
    with pytest.raises(ValueError, match="integrity check failed"):
        namespace["verify"](lock, artifacts, "amd64")


def test_executor_docker_context_is_minimized() -> None:
    ignored = (EXECUTOR / "Dockerfile.dockerignore").read_text(encoding="utf-8")
    assert ignored.startswith("**\n")
    assert "!dist/executor-wheelhouse/**" in ignored
    assert "!dist/executor-native/**" in ignored
    assert "!docker/executor/requirements.lock" in ignored


def test_audited_base_environment_contains_no_injection_variables() -> None:
    names = {entry.partition("=")[0] for entry in AUDITED_IMAGE_ENV}
    assert names == {"PATH", "GPG_KEY", "PYTHON_VERSION", "PYTHON_SHA256"}
    assert names.isdisjoint(
        {"LD_PRELOAD", "LD_AUDIT", "LD_LIBRARY_PATH", "PYTHONPATH", "PYTHONHOME"}
    )
